config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'pages#home'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/admin_dashboard', to: 'pages#admin_dashboard'
  get '/orders/confirmation', to: "orders#confirmation"
  resources :orders, only: [:update]
  get '/maps/classics_challenge', to: 'maps#classics_challenge'
  resources :maps, only: [:new, :create] do
    resources :orders, only: [:new, :create] do
    	resources :payments, only: [:new, :create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :orders
  monetize :price_cents
  attr_accessor :strava_id

  accepts_nested_attributes_for :orders
  mount_uploader :image, PhotoUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :map
  belongs_to :user
  monetize :amount_cents
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def default_url_options
	  { host: ENV["DOMAIN"] || ENV["APP_HOST"] }
	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def new
	    if (@token = params[:code])

		  	@response = JSON.parse(RestClient.post("https://www.strava.com/oauth/token?client_id=38164&client_secret=0b227c9387f9b5a8ce9b9833387192004098d95c&code=#{@token}&grant_type=authorization_code", {}))
		  	@access_token = @response["access_token"]
		  	@athlete_id = @response["athlete"]["id"]
		  	# @stats = JSON.parse(RestClient.get("https://www.strava.com/api/v3/athletes/#{@athlete_id}/stats?page=&per_page=", {Authorization: "Bearer #{@access_token}"}))
		  	# @biggest_ride = @stats["biggest_ride_distance"]

		  	@activities = JSON.parse(RestClient.get("https://www.strava.com/api/v3/athlete/activities?per_page=100", {Authorization: "Bearer #{@access_token}"}))

				@user = User.find_or_initialize_by(strava_id: "#{@athlete_id}")
				@user.save
		  	@map = Map.new
		  	@map.orders << Order.new
	    else
	      @map =Map.new
	    end
	end

	def classics_challenge
		if (@token = params[:code])

			@response = JSON.parse(RestClient.post("https://www.strava.com/oauth/token?client_id=38164&client_secret=0b227c9387f9b5a8ce9b9833387192004098d95c&code=#{@token}&grant_type=authorization_code", {}))
			@access_token = @response["access_token"]
			@athlete_id = @response["athlete"]["id"]
			# @stats = JSON.parse(RestClient.get("https://www.strava.com/api/v3/athletes/#{@athlete_id}/stats?page=&per_page=", {Authorization: "Bearer #{@access_token}"}))
			# @biggest_ride = @stats["biggest_ride_distance"]

			@activities = JSON.parse(RestClient.get("https://www.strava.com/api/v3/athlete/activities?per_page=200", {Authorization: "Bearer #{@access_token}"}))
			user_infos = JSON.parse(RestClient.get("https://www.strava.com/api/v3/athlete", {Authorization: "Bearer #{@access_token}"}))
			@user_name = user_infos["username"]
			@user = User.find_or_initialize_by(strava_id: "#{@athlete_id}")
			@user.save
			@map = Map.new
			@map.orders << Order.new
		else
			@map = Map.new
		end
	end

	def create
		@map = Map.new(map_params)
		if map_params[:format] == "21x30cm - 25€"
      @map.price_cents = 2500
		elsif map_params[:format] == "30x45cm - 39€"
      @map.price_cents = 3900
    elsif map_params[:format] == "50x70cm - 55€"
      @map.price_cents = 5500
    end
    @map.orders.last.amount_cents = @map.price_cents
		@map.orders.last.user = User.find_by(strava_id: map_params[:strava_id])

		if @map.save
			# redirect_to new_map_order_payment_path(@map, @map.orders.last)
			render json: @map.orders.last
		else
			render :new
		end
	end

	private

	def map_params
		params.permit(:title, :image, :map_url, :format, :distance, :time, :elevation, :speed, :strava_id, orders_attributes:[:first_name, :last_name, :email, :phone, :address, :post_code, :city, :country, :map_sku, :state])
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:update, :cancel_shipment]

  def confirmation
  end

  def update
    if @order.shipped === false
      @order.shipped = true
      @order.update(order_params)
      @order.save!
      mail = OrderMailer.with(order: @order).shipment
      mail.deliver_now
      redirect_to admin_dashboard_path
    elsif @order.shipped === true
      @order.shipped = false
      @order.tracking_number = nil
      @order.save!
      redirect_to admin_dashboard_path
    end
  end

  def cancel_shipment
  end

  private

  def set_map
    @map = Map.find(params[:map_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :address, :image, :price, :tracking_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'rest-client'
  require 'json'
  before_action :authenticate_admin!, only: :admin_dashboard

  def home
  end

  def admin_dashboard
  	@orders = Order.all
    @users = User.all
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :set_order

	  def new
	  end

	  def create
	    customer = Stripe::Customer.create(
	        source: params[:stripeToken],
	        email:  params[:stripeEmail]
	      )

	      charge = Stripe::Charge.create(
	        customer:     customer.id,   # You should store this customer id and re-use it.
	        amount:       @order.amount_cents,
	        description:  "Payment for map ##{@order.map_sku} for order ##{@order.id}",
	        currency:     @order.amount.currency
	      )

	      @order.update(payment: charge.to_json, state: 'paid')
	   	  mail = OrderMailer.with(order: @order).confirmation
	   	  mail.deliver_now
	      redirect_to "/orders/confirmation"

	    rescue Stripe::CardError => e
	      flash[:alert] = e.message
	      redirect_to new_map_order_payment_path(@order.map, @order)
	  end

	private

	  def set_order
	    @order = Order.find(params[:order_id])
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i&display=swap" rel="stylesheet">

    <title>Posterity - Print a poster of the itineraries you're the most proud of</title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149502589-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-149502589-1');
    </script>

    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="a60edc0a-d3b4-49d0-9109-2fded2fd40f8";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();
    </script>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '531921527353841');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=531921527353841&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# stylesheet_pack_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico'%>

    <!-- Hotjar Tracking Code for www.forposterity.io -->
    <script>
      (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:1538484,hjsv:6};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= simple_form_for(@map) do |f| %>
    <%= f.input :format, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :map_url, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :title, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :distance, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :speed, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :elevation, :as => :hidden, :input_html => { :value => "" } %>
    <%= f.input :time, :as => :hidden, :input_html => { :value => "" } %>
      <%= f.simple_fields_for :orders do |orders_form| %>
          <%= orders_form.input :first_name %>
          <%= orders_form.input :last_name %>
          <%= orders_form.input :email %>
          <%= orders_form.input :phone %>
          <%= orders_form.input :address %>
          <%= orders_form.input :post_code %>
          <%= orders_form.input :city %>
          <%= orders_form.input :country, as: :country, priority: ['FR'] %>
          <%= orders_form.input :strava_id, :as => :hidden, :input_html => { :value => @athlete_id } %>
      <% end %>
<% end %>

app/views/maps/classics_challenge.html.erb
<div id="new-map-body" class="cc-body">
  <div class="container-fluid py-5">
    <div class="row">
      <div class="display-map col-5 my-auto ml-auto">
        <% if @activities %>
          <div id="classics_challenge_map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <% else %>
          <div id="classics_challenge_default"></div>
        <% end %>
      </div>
      <div id="customize-map" class="col-5 my-auto mr-auto">
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-customize-map" role="tabpanel" aria-labelledby="pills-home-tab">
            <div id="accordion-style">
              <div class='right'>
                <div class='app'>
                  <div class='app_inner'>
                    <input id='tab-1' name='buttons' type='radio' disabled="true">
                    <label for='tab-1'>
                      <div class='app_inner__tab'>
                        <h2><i id="cc-icon"><%= image_tag "logo-cc.png", class: "logo-cc"%></i>POSTER FINISHER 2019</h2>
                      </div>
                    </label>
                    <input id='tab-2' name='buttons' type='radio' checked>
                    <label for='tab-2'>
                      <div class='app_inner__tab'>
                        <h2>La récompense</h2>
                        <div class='tab_right'>
                          <div class="m-3">
                            <p id="classic-challenge-text">Un joli cadeau à s'offrir que ce poster personnalisé, si vous avez aimé la saison 3 des Classics Challenge. Chez Posterity, on l'a roulée et on a adoré. La procédure est hyper simple. Connectez-vous à votre Strava, sélectionnez vos activités, saisissez votre nom, c'est tout.</p>
                          <!-- <h3>Choisissez un style pour votre poster</h3> -->
                            <!-- <input class="btn btn-cc-yellow" id='ck2kdyw7z0e5t1ck0ffszwwh3' type='button' name='rtoggle' data-toggle="tooltip" data-placement="top" title="CC-yellow">
                            <input class="btn btn-cc-white" id='other' type='button' name='rtoggle' data-toggle="tooltip" data-placement="top" title="CC-white"> -->
                            <div class="row justify-content-center mr-0">
                            <% if @activities %>
                              <% if @activities.length > 0 %>
                                <div class="traces-list flex-track">
                                  <% @activities.first(500).each do |activity|%>
                                     <div class="content"><span class="btn btn-track activity-cc-btn p-2 m-2" id="activity_<%= @activities.index(activity) + 1 %>" data-id="<%= @activities.index(activity) + 1 %>" data-toggle="tooltip" data-title="<%= activity["name"] %>"data-polyline="<%= activity['map']['summary_polyline'] %>" data-image="<%= activity["type"] %>" data-distance="<%= activity["distance"]%>" data-time="<%= activity["moving_time"]%>" data-speed="<%= activity["average_speed"] %>" data-elevation="<%= activity["total_elevation_gain"] %>"><%= activity["name"] %></span></div>
                                  <% end %>
                                  <a href="#" id="loadMoreCc" class="btn-posterity">Load More</a>
                                </div>
                                <div class="input-group-prepend fields-input title-map-input mt-3">
                                  <input class="ride-title form-control" placeholder="Ajoutez votre nom sur le poster" type="text" name="ride-name" value="<%= @user_name %>">
                                </div>
                              <% else %>
                                <h3>Aucune activité publique liée à ce compte strava</h3>
                              <% end %>
                            <% else %>
                              <div class="row justify-content-center">
                                  <a href="http://www.strava.com/oauth/authorize?client_id=38164&response_type=code&redirect_uri=<%= ENV["APP_HOST"] %>/maps/classics_challenge&approval_prompt=force&scope=read,activity:read"><div class="btn-posterity" id="test">Connectez votre Strava</div></a>
                              </div>
                            <% end %>
                            </div>
                            <%= simple_form_for(@map) do |f| %>
                              <%= f.input_field :format, :as => :hidden, collection: ['21x30cm - 25€', '30x45cm - 39€', '50x70cm - 55€'], class: 'value-format', :checked => ['30x45cm - 39€'].first %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </label>
                    <% if @activities %>
                      <input id='tab-4' name='buttons' type='radio' disabled="true">
                      <label for='tab-4'>
                        <div class='app_inner__tab'>
                          <h2>
                            <h3>Format A3 - Papier d'Art Old Mill 300g - (livraison comprise)</h3>
                            <div id="order-cc-button" class="btn-posterity">Commandez - 39.99€</div>
                          </h2>
                        </div>
                      </label>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="pills-checkout" role="tabpanel" aria-labelledby="pills-profile-tab">
              <div id="accordion-style">
                <div class='right'>
                  <div class='app'>
                    <div class='app_inner'>
                      <input id='tab-5' name='buttons' type='radio'>
                      <label for='tab-5'>
                        <div class='order'>
                          <h2>Renseignez vos informations pour finaliser la commande</h2>
                          <div class="row justify-content-center m-3 box-order">
                            <div id="back-cc-button" class="btn-posterity"><i class="fas fa-arrow-left"></i>Retour à la personnalisation</div>
                            <%= simple_form_for(@map) do |f| %>
                              <%= f.input :format, :as => :hidden, :input_html => { :value => "30x45cm - 39€" } %>
                              <%= f.input :map_url, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.input :title, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.input :distance, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.input :speed, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.input :elevation, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.input :time, :as => :hidden, :input_html => { :value => "" } %>
                              <%= f.simple_fields_for :orders do |orders_form| %>
                                <%= orders_form.input :first_name %>
                                <%= orders_form.input :last_name %>
                                <%= orders_form.input :email %>
                                <%= orders_form.input :phone %>
                                <%= orders_form.input :address %>
                                <%= orders_form.input :post_code %>
                                <%= orders_form.input :city %>
                                <%= orders_form.input :country, as: :country, priority: ['FR'] %>
                                <%= orders_form.input :strava_id, :as => :hidden, :input_html => { :value => "Unknown" } %>
                              <% end %>
                            <% end %>
                            <div class="checkout d-flex justify-content-around">
                              <button class="btn-posterity order-btn" id="submit_cc_map">Commandez - 39.99€</button>
                            </div>
                          </div>
                        </div>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
    <div class="openstreetmaps-credit">
      Map data by <a href="http://www.openstreetmap.org/" target="blank">OpenStreetMaps contributors</a>
    </div>
  </div>
</div>

app/views/pages/admin_dashboard.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="orders-tab" data-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="true">Orders</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="users-tab" data-toggle="tab" href="#users" role="tab" aria-controls="users" aria-selected="false">Users</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="orders" role="tabpanel" aria-labelledby="orders-tab">
  	<h1>Last Orders</h1>
		<div class="mr-3 ml-3">
		<table class="table">
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">Date</th>
		      <th scope="col">Command #</th>
		      <th scope="col">Status</th>
		      <th scope="col">Price</th>
		      <th scope="col">Map-Url</th>
		      <th scope="col">Title</th>
		      <th scope="col">Elev</th>
		      <th scope="col">Dist</th>
		      <th scope="col">Time</th>
		      <th scope="col">Speed</th>
		      <th scope="col">Address</th>
		      <th scope="col">Name</th>
		      <th scope="col">Email</th>
		      <th scope="col">Phone</th>
		      <th scope="col">Strava Profile</th>
		      <th scope="col">Actions</th>
		    </tr>
		  </thead>
		  <tbody>
			<% @orders.sort_by {|order| order.id}.reverse.each do |order| %>
			    <tr>
			      <td><%= order.created_at %></td>
			      <td><%= order.id %></td>
			      <td>
			      	<% if order.state === "paid" %>
			      		<span class="badge badge-success">Paid</span>
					<% else %>
						<span class="badge badge-warning">Pending</span>
					<% end %>
			      </td>
			      <td><%= order.map.price_cents / 100 %>€</td>
			      <td><a href="<%= order.map.map_url %>" target="blank">MB_Url</a>  <a href="<%= order.map.image %>" target="blank">Pdf</a></td>
			      <td><%= order.map.title%></td>
			      <td>
			      	<% if order.map.elevation%>
			      		<%= order.map.elevation %>
					<% else %>
						x
					<% end %>
			      </td>
			      <td>
			      	<% if order.map.distance%>
			      		<%= order.map.distance / 1000 %> km
					<% else %>
						x
					<% end %>
			      </td>
			      <td>
			      	<% if order.map.time %>
			      		<%= [order.map.time / 3600, order.map.time / 60 % 60, order.map.time % 60].map{|t| t.to_s.rjust(2,'0')}.join(':') %>
					<% else %>
						x
					<% end %>
			      </td>
			      <td>
			      	<% if order.map.speed %>
			      		<%= order.map.speed / 100 * 3.6 %>km/h
					<% else %>
						x
					<% end %>
			      </td>
			      <td>
		          <%= order.address%>
		          <%= order.post_code%>
		          <%= order.city%>
		          <%= order.country%>
						</td>
			      <td><%= order.first_name%>, <%= order.last_name%></td>
			      <td><%= order.email%></td>
			      <td><%= order.phone%></td>
			      <td><a href="https://www.strava.com/athletes/<%= order.user.strava_id%>" target="blank"><i class="fab fa-strava"></i></a></td>
			      <td>
					<% if order.shipped %>
						<span class="badge badge-success">Shipped</span>
						<%= link_to(order_path(order), class: "btn btn-light btn-sm", method: :put, data: { confirm: "Are you sure?" }) do %>
							<i class="fas fa-undo-alt"></i>
						<% end %>
			       <% else %>
			       		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
			       		  	<i class="fas fa-paper-plane"></i>
			       		</button>
			       		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			       		  <div class="modal-dialog" role="document">
			       		    <div class="modal-content">
			       		      <div class="modal-header">
			       		        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
			       		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			       		          <span aria-hidden="true">&times;</span>
			       		        </button>
			       		      </div>
			       		      <div class="modal-body">
			       		      	<%= simple_form_for(order) do |f| %>
			       		      		<%= f.input :tracking_number %>
			       		      		<%= f.button :submit, class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
			       		      	<% end %>
			       		      </div>
			       		      <div class="modal-footer">
			       		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			       		      </div>
			       		    </div>
			       		  </div>
			       		</div>
			       <% end %>
			      </td>
			    </tr>
			<% end %>
		  </tbody>
		</table>
		</div>
  </div>
  <div class="tab-pane fade" id="users" role="tabpanel" aria-labelledby="users-tab">
  	<h1>All users</h1>
		<div class="mr-3 ml-3">
		<table class="table">
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">Creation date</th>
		      <th scope="col">Strava Link</th>
		      <th scope="col">First Name / Name</th>
		    </tr>
		  </thead>
			<tbody>
			<% @users.sort_by {|user| user.id}.reverse.each do |user| %>
			    <tr>
			      <td><%= user.created_at %></td>
			      <td><a href="https://www.strava.com/athletes/<%= user.strava_id%>" target="blank"><i class="fab fa-strava"></i></a></td>
			      <td>
							<% if user.orders.length > 0 %>
								<%= user.orders.first.first_name %><%= user.orders.first.last_name %>
							<% else %>
								<p>X</p>
							<% end %>
						</td>
			    </tr>
			<% end %>
		  </tbody>
		</table>
		</div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="order-page d-flex justify-content-center align-items-center rounded">
  <div class="order-container">
    <div class="order-confirmed">
        <h2>Last step to purchase your awesome poster</h2>
    </div>
    <div class="container order-text">
      <article>
          <label class="amount">
            <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
          </label>
        </article>
        <%= form_tag map_order_payments_path(@order.map, @order) do %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="My Map"
          data-email="<%= @order.email %>"
          data-description="Map #<%= @order.map_sku %>"
          data-amount="<%= @order.amount_cents %>"
          data-currency="<%= @order.amount.currency %>"></script>
        <% end %>
    </div>
    
  </div>
</div>
<%= render 'shared/footer' %>